copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
baseurl = "https://emartinelli.github.io/"
title = "Elvio Martinelli"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 10

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = false

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = true

# Metadata mostly used in document's head
description = "Elvio Martinelli tech blog"
keywords = "tech, blog, software"
images = [""]

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]
[languages.en]
[languages.en.params]
title = "Elvio Martinelli"
homeSubtitle = "Software Engineer"
subtitle = "Software Engineer"
keywords = ""
readOtherPosts = "Read other posts"
[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"

[languages.pt-br]
[languages.pt-br.params]
title = "Elvio Martinelli"
homeSubtitle = "Engenheiro de Software"
subtitle = "Engenheiro de Software"
keywords = ""
readOtherPosts = "Leia outros posts"
[[languages.pt-br.menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"

[params.logo]
logoText = "$ cd ~"
logoHomeLink = "/"

[[params.social]]
name = "github"
url = "https://github.com/emartinelli"
[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/emartinelli"
[[params.social]]
name = "dev"
url = "https://dev.to/emartinelli"
